import { Boxes, ClipboardList, KanbanSquare, ReceiptText, Truck } from "lucide-react";
import { materialOptions, unitOptions } from "../lib/statusWorkflow.js";
import {
  orderDefaultColumns,
  productionScheduleColumns,
  finalDeliveryField,
  finalDeliveryStatusOptions,
} from "../lib/columnDefs.js";

const tableConfigs = {
  products: {
    label: "产品录入",
    icon: Boxes,
    rowLabel: "产品",
    defaultColumns: [
      { field: "name", headerName: "产品名称", width: 150, required: true },
      { field: "spec", headerName: "规格尺寸", width: 150 },
      { field: "material", headerName: "泡沫材质", width: 130, type: "select", options: materialOptions },
      { field: "unit", headerName: "单位", width: 90, type: "select", options: unitOptions },
      {
        field: "unitPrice",
        headerName: "单价",
        width: 110,
        type: "number",
      },
      { field: "moq", headerName: "起订量", width: 110, type: "number" },
      { field: "remark", headerName: "备注", flex: 1, minWidth: 160 },
    ],
    emptyRow: {
      name: "新泡沫产品",
      spec: "",
      material: "EPS",
      unit: "件",
      unitPrice: 0,
      moq: 0,
      remark: "",
    },
  },
  orders: {
    label: "订单录入 / 跟进",
    icon: ClipboardList,
    rowLabel: "订单",
    defaultColumns: orderDefaultColumns,
    emptyRow: {
      orderNo: "",
      date: "",
      product: "",
      quantity: 0,
      amount: 0,
      dueDate: "",
      status: "未完成",
      followUp: "",
    },
  },
  productionSchedule: {
    label: "排产看板",
    icon: KanbanSquare,
    rowLabel: "排产订单",
    defaultColumns: [
      ...orderDefaultColumns,
      ...productionScheduleColumns,
    ],
    emptyRow: {},
    sourceTableKey: "orders",
    disableRowCreate: true,
  },
  historyOrders: {
    label: "历史订单",
    icon: ClipboardList,
    rowLabel: "历史订单",
    defaultColumns: orderDefaultColumns,
    emptyRow: {},
    sourceTableKey: "orders",
    readOnly: true,
  },
  deliveries: {
    label: "送货单草稿",
    icon: Truck,
    rowLabel: "送货单草稿",
    defaultColumns: [
      {
        field: "deliveryNo",
        headerName: "送货单号",
        width: 150,
        required: true,
      },
      { field: "date", headerName: "送货日期", width: 130, type: "date" },
    ],
    emptyRow: {
      deliveryNo: "",
      date: "",
      status: "未送",
      [finalDeliveryField]: false,
    },
  },
  finalDeliveries: {
    label: "送货单",
    icon: Truck,
    rowLabel: "送货单",
    defaultColumns: [
      {
        field: "deliveryNo",
        headerName: "送货单号",
        width: 150,
        required: true,
      },
      { field: "date", headerName: "送货日期", width: 130, type: "date" },
      {
        field: "status",
        headerName: "状态",
        width: 110,
        type: "select",
        options: finalDeliveryStatusOptions,
      },
    ],
    emptyRow: {},
    sourceTableKey: "deliveries",
    disableRowCreate: true,
  },
  materialCosts: {
    label: "物料档案",
    icon: ReceiptText,
    rowLabel: "物料",
    defaultColumns: [
      { field: "materialName", headerName: "物料名称", width: 150, required: true },
      { field: "unit", headerName: "单位", width: 90, type: "select", options: unitOptions },
      { field: "unitCost", headerName: "成本单价", width: 120, type: "number" },
      { field: "supplier", headerName: "供应商", width: 150 },
      { field: "remark", headerName: "备注", flex: 1, minWidth: 160 },
    ],
    emptyRow: {
      materialName: "新物料",
      unit: "件",
      unitCost: 0,
      supplier: "",
      remark: "",
    },
  },
  costEntries: {
    label: "成本录入",
    icon: ReceiptText,
    rowLabel: "成本记录",
    defaultColumns: [
      { field: "date", headerName: "录入日期", width: 130, type: "date" },
      { field: "materialName", headerName: "物料名称", width: 150 },
      { field: "quantity", headerName: "数量", width: 100, type: "number" },
      { field: "unit", headerName: "单位", width: 90 },
      { field: "unitCost", headerName: "成本单价", width: 120, type: "number" },
      { field: "amount", headerName: "成本金额", width: 120, type: "number" },
      { field: "photo", headerName: "照片证明", width: 130, type: "image", editable: false },
      { field: "enteredBy", headerName: "录入人", width: 120, editable: false },
      { field: "enteredAt", headerName: "录入时间", width: 170, type: "datetime", editable: false },
      { field: "note", headerName: "备注", flex: 1, minWidth: 160 },
    ],
    emptyRow: {
      date: "",
      materialName: "",
      quantity: 0,
      unit: "",
      unitCost: 0,
      amount: 0,
      photo: "",
      enteredBy: "",
      enteredAt: "",
      note: "",
    },
  },
};

export { tableConfigs };
