import { Boxes, ClipboardList, CreditCard, FileText, KanbanSquare, ReceiptText, Truck } from "lucide-react";
import { materialOptions, unitOptions } from "../lib/statusWorkflow.js";
import {
  orderDefaultColumns,
  productionScheduleColumns,
  finalDeliveryField,
  finalDeliveryStatusOptions,
} from "../lib/columnDefs.js";

const tableConfigs = {
  products: {
    label: "产品录入",
    icon: Boxes,
    rowLabel: "产品",
    defaultColumns: [
      { field: "name", headerName: "产品名称", width: 150, required: true },
      { field: "spec", headerName: "规格尺寸", width: 150 },
      { field: "material", headerName: "泡沫材质", width: 130, type: "select", options: materialOptions },
      { field: "unit", headerName: "单位", width: 90, type: "select", options: unitOptions },
      {
        field: "unitPrice",
        headerName: "单价",
        width: 110,
        type: "number",
      },
      { field: "moq", headerName: "起订量", width: 110, type: "number" },
      { field: "remark", headerName: "备注", flex: 1, minWidth: 160 },
    ],
    emptyRow: {
      name: "新泡沫产品",
      spec: "",
      material: "EPS",
      unit: "件",
      unitPrice: 0,
      moq: 0,
      remark: "",
    },
  },
  orders: {
    label: "订单录入 / 跟进",
    icon: ClipboardList,
    rowLabel: "订单",
    defaultColumns: orderDefaultColumns,
    emptyRow: {
      orderNo: "",
      date: "",
      product: "",
      quantity: 0,
      amount: 0,
      dueDate: "",
      status: "未完成",
      followUp: "",
    },
  },
  productionSchedule: {
    label: "排产看板",
    icon: KanbanSquare,
    rowLabel: "排产订单",
    defaultColumns: [
      ...orderDefaultColumns,
      ...productionScheduleColumns,
    ],
    emptyRow: {},
    sourceTableKey: "orders",
    disableRowCreate: true,
  },
  historyOrders: {
    label: "历史订单",
    icon: ClipboardList,
    rowLabel: "历史订单",
    defaultColumns: orderDefaultColumns,
    emptyRow: {},
    sourceTableKey: "orders",
    readOnly: true,
  },
  deliveries: {
    label: "送货单草稿",
    icon: Truck,
    rowLabel: "送货单草稿",
    defaultColumns: [
      {
        field: "deliveryNo",
        headerName: "送货单号",
        width: 150,
        required: true,
      },
      { field: "date", headerName: "送货日期", width: 130, type: "date" },
    ],
    emptyRow: {
      deliveryNo: "",
      date: "",
      status: "未送",
      [finalDeliveryField]: false,
    },
  },
  finalDeliveries: {
    label: "送货单",
    icon: Truck,
    rowLabel: "送货单",
    defaultColumns: [
      {
        field: "deliveryNo",
        headerName: "送货单号",
        width: 150,
        required: true,
      },
      { field: "date", headerName: "送货日期", width: 130, type: "date" },
      {
        field: "status",
        headerName: "状态",
        width: 110,
        type: "select",
        options: finalDeliveryStatusOptions,
      },
    ],
    emptyRow: {},
    sourceTableKey: "deliveries",
    disableRowCreate: true,
  },
  materialCosts: {
    label: "物料档案",
    icon: ReceiptText,
    rowLabel: "物料",
    defaultColumns: [
      { field: "materialName", headerName: "物料名称", width: 150, required: true },
      { field: "unit", headerName: "单位", width: 90, type: "select", options: unitOptions },
      { field: "unitCost", headerName: "成本单价", width: 120, type: "number" },
      { field: "priceUpdatedAt", headerName: "价格更新时间", width: 170, type: "datetime", editable: false },
      { field: "priceHistory", headerName: "价格历史", width: 220, editable: false },
      { field: "supplier", headerName: "供应商", width: 150 },
      { field: "remark", headerName: "备注", flex: 1, minWidth: 160 },
    ],
    emptyRow: {
      materialName: "新物料",
      unit: "件",
      unitCost: 0,
      priceUpdatedAt: "",
      priceHistory: "",
      supplier: "",
      remark: "",
    },
  },
  statements: {
    label: "对账单",
    icon: FileText,
    rowLabel: "对账单",
    defaultColumns: [
      { field: "statementNo", headerName: "对账单号", width: 150, editable: false },
      { field: "date", headerName: "对账日期", width: 130, type: "date" },
      { field: "deliveryNos", headerName: "关联送货单", width: 180, editable: false },
      { field: "lineCount", headerName: "明细数", width: 90, type: "number", editable: false },
      { field: "amount", headerName: "对账金额", width: 120, type: "number", editable: false },
      { field: "paidAmount", headerName: "已付金额", width: 120, type: "number", editable: false },
      { field: "unpaidAmount", headerName: "未付金额", width: 120, type: "number", editable: false },
      { field: "status", headerName: "状态", width: 110, type: "select", options: ["未收款", "部分收款", "已收款"] },
      { field: "createdAt", headerName: "创建时间", width: 170, type: "datetime", editable: false },
      { field: "note", headerName: "备注", flex: 1, minWidth: 160 },
    ],
    emptyRow: {
      statementNo: "",
      date: "",
      deliveryNos: "",
      lineCount: 0,
      amount: 0,
      paidAmount: 0,
      unpaidAmount: 0,
      status: "未收款",
      createdAt: "",
      note: "",
    },
  },
  payments: {
    label: "收款记录",
    icon: CreditCard,
    rowLabel: "收款",
    defaultColumns: [
      { field: "date", headerName: "收款日期", width: 130, type: "date" },
      { field: "statementNo", headerName: "对应对账单", width: 150 },
      { field: "amount", headerName: "收款金额", width: 120, type: "number" },
      { field: "method", headerName: "付款方式", width: 120, type: "select", options: ["现金", "银行转账", "支票", "其他"] },
      { field: "receivedBy", headerName: "收款人", width: 120 },
      { field: "createdAt", headerName: "录入时间", width: 170, type: "datetime", editable: false },
      { field: "note", headerName: "备注", flex: 1, minWidth: 160 },
    ],
    emptyRow: {
      date: "",
      statementNo: "",
      amount: 0,
      method: "银行转账",
      receivedBy: "",
      createdAt: "",
      note: "",
    },
  },
  costEntries: {
    label: "成本录入",
    icon: ReceiptText,
    rowLabel: "成本记录",
    defaultColumns: [
      { field: "date", headerName: "录入日期", width: 130, type: "date" },
      { field: "materialName", headerName: "物料名称", width: 150 },
      { field: "quantity", headerName: "数量", width: 100, type: "number" },
      { field: "unit", headerName: "单位", width: 90 },
      { field: "unitCost", headerName: "成本单价", width: 120, type: "number" },
      { field: "amount", headerName: "成本金额", width: 120, type: "number" },
      { field: "photo", headerName: "照片证明", width: 130, type: "image", editable: false },
      {
        field: "approvalStatus",
        headerName: "审批状态",
        width: 110,
        type: "select",
        options: ["待审核", "已通过", "已拒绝"],
      },
      { field: "approvedBy", headerName: "审批人", width: 120, editable: false },
      { field: "approvedAt", headerName: "审批时间", width: 170, type: "datetime", editable: false },
      { field: "approvalNote", headerName: "审批备注", width: 150 },
      { field: "enteredBy", headerName: "录入人", width: 120, editable: false },
      { field: "enteredAt", headerName: "录入时间", width: 170, type: "datetime", editable: false },
      { field: "note", headerName: "备注", flex: 1, minWidth: 160 },
    ],
    emptyRow: {
      date: "",
      materialName: "",
      quantity: 0,
      unit: "",
      unitCost: 0,
      amount: 0,
      photo: "",
      approvalStatus: "待审核",
      approvedBy: "",
      approvedAt: "",
      approvalNote: "",
      enteredBy: "",
      enteredAt: "",
      note: "",
    },
  },
};

export { tableConfigs };
